// Code generated by Slice Machine. DO NOT EDIT.

import CtaSlice from './CtaSlice';
import Hero from './Hero';
import ImageLeftAndText from './ImageLeftAndText';
import New from './New';
import TestNewScreenshots from './TestNewScreenshots';

export {
	CtaSlice,
	Hero,
	ImageLeftAndText,
	New,
	TestNewScreenshots,
};

export const components = {
	cta_slice: CtaSlice,
	hero: Hero,
	image_left_and_text: ImageLeftAndText,
	new: New,
	test_new_screenshots: TestNewScreenshots,
};
